apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::106649693507:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AXC123EP8Z26
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::106649693507:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-12T14:25:05Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-12T14:25:05Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-05-12T14:31:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2879"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 14ab4ccf-194f-4110-a378-9d20a668372a
